export const ISO = [
  { code: "AF", name: "Afghanistan", korName: "아프카니스탄" },
  { code: "AF", name: "Afghanistan", korName: "아프가니스탄" },
  { code: "DZ", name: "Algeria", korName: "알제리" },
  { code: "AD", name: "Andorra", korName: "안도라" },
  { code: "AI", name: "Anguilla", korName: "앙귈라" },
  { code: "AG", name: "Antigua and Barbuda", korName: "안티가바부다" },
  { code: "AM", name: "Armenia", korName: "아르메니아" },
  { code: "AU", name: "Australia", korName: "호주" },
  { code: "AZ", name: "Azerbaijan", korName: "아제르바이잔" },
  { code: "BH", name: "Bahrain", korName: "바레인" },
  { code: "BB", name: "Barbados", korName: "바베이도스" },
  { code: "BE", name: "Belgium", korName: "벨기에" },
  { code: "BJ", name: "Benin", korName: "베닝" },
  { code: "BT", name: "Bhutan", korName: "부탄" },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    korName: "보스니아 헤르체고비나",
  },
  { code: "BV", name: "Bouvet Island", korName: "보빗군도" },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    korName: "영령 인도양",
  },
  { code: "BG", name: "Bulgaria", korName: "불가리아" },
  { code: "BI", name: "Burundi", korName: "부룬디" },
  { code: "CM", name: "Cameroon", korName: "카메룬" },
  { code: "CV", name: "Cabo Verde", korName: "카보베르데" },
  {
    code: "CF",
    name: "Central African Republic",
    korName: "중앙아프리카",
  },
  {
    code: "CF",
    name: "CAR",
    korName: "중앙아프리카",
  },
  {
    code: "CF",
    name: "Central African Republic",
    korName: "중앙아프리카공화국",
  },
  { code: "CL", name: "Chile", korName: "칠레" },
  {
    code: "CX",
    name: "Christmas Island",
    korName: "크리스마스 아일랜드",
  },
  { code: "CO", name: "Colombia", korName: "콜롬비아" },
  { code: "CG", name: "Congo", korName: "콩고공화국" },
  { code: "CG", name: "Congo", korName: "콩고" },
  { code: "CR", name: "Costa Rica", korName: "코스타리카" },
  { code: "HR", name: "Croatia", korName: "크로아티아" },
  { code: "CY", name: "Cyprus", korName: "사이프러스" },
  { code: "DK", name: "Denmark", korName: "덴마크" },
  { code: "DM", name: "Dominica", korName: "도미니카" },
  { code: "TL", name: "Timor-Leste", korName: "동티모르" },
  { code: "EG", name: "Egypt", korName: "이집트" },
  { code: "GQ", name: "Equatorial Guinea", korName: "적도기니" },
  { code: "EE", name: "Estonia", korName: "에스토니아" },
  {
    code: "FK",
    name: "Falkland Islands-Malvinas",
    korName: "포클랜드 군도",
  },
  {
    code: "FK",
    name: "Falkland Islands",
    korName: "포클랜드 제도",
  },
  { code: "FJ", name: "Fiji", korName: "피지" },
  { code: "FR", name: "France", korName: "프랑스" },
  { code: "PF", name: "French Polynesia", korName: "폴리네시아 (프랑스령)" },
  { code: "GA", name: "Gabon", korName: "가봉" },
  { code: "GE", name: "Georgia", korName: "조지아" },
  { code: "GH", name: "Ghana", korName: "가나" },
  { code: "GR", name: "Greece", korName: "그리스" },
  { code: "GD", name: "Grenada", korName: "그레나다" },
  { code: "GU", name: "Guam", korName: "괌" },
  { code: "GN", name: "Guinea", korName: "기니" },
  { code: "GY", name: "Guyana", korName: "기아나" },
  { code: "HN", name: "Honduras", korName: "온두라스" },
  { code: "HU", name: "Hungary", korName: "헝가리" },
  { code: "IN", name: "India", korName: "인도" },
  { code: "IR", name: "Iran", korName: "이란" },
  { code: "IE", name: "Ireland", korName: "아일랜드" },
  { code: "IT", name: "Italy", korName: "이탈리아" },
  { code: "JP", name: "Japan", korName: "일본" },
  { code: "KZ", name: "Kazakhstan", korName: "카자흐스탄" },
  { code: "KI", name: "Kiribati", korName: "키리바티" },
  { code: "KI", name: "Kiribati", korName: "키리바시" },
  { code: "KR", name: "S. Korea", korName: "대한민국" },
  { code: "KR", name: "South Korea", korName: "대한민국" },
  { code: "KG", name: "Kyrgyzstan", korName: "키르기스스탄" },
  { code: "KG", name: "Kyrgyzstan", korName: "키르기즈스탄" },
  { code: "LV", name: "Latvia", korName: "라트비아" },
  { code: "LS", name: "Lesotho", korName: "레소토" },
  { code: "LY", name: "Libya", korName: "리비아" },
  { code: "LT", name: "Lithuania", korName: "리투아니아" },
  { code: "MO", name: "Macao", korName: "마카오" },
  { code: "MG", name: "Madagascar", korName: "마다가스카르" },
  { code: "MY", name: "Malaysia", korName: "말레이시아" },
  { code: "ML", name: "Mali", korName: "말리" },
  { code: "MH", name: "Marshall Islands", korName: "마셜제도" },
  { code: "MH", name: "Marshall Islands", korName: "마샬제도" },
  { code: "MR", name: "Mauritania", korName: "모리타니아" },
  { code: "YT", name: "Mayotte", korName: "메요트" },
  { code: "FM", name: "Micronesia", korName: "마이크로네시아" },
  { code: "FM", name: "Micronesia", korName: "미크로네시아" },
  { code: "MC", name: "Monaco", korName: "모나코" },
  { code: "MS", name: "Montserrat", korName: "몬트세라트" },
  { code: "MZ", name: "Mozambique", korName: "모잠비크" },
  { code: "NA", name: "Namibia", korName: "나미비아" },
  { code: "NP", name: "Nepal", korName: "네팔" },
  { code: "AN", name: "Netherlands Antilles", korName: "네덜란드 열도" },
  { code: "NZ", name: "New Zealand", korName: "뉴질랜드" },
  { code: "NE", name: "Niger", korName: "니제르" },
  { code: "NU", name: "Niue", korName: "니우에" },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    korName: "북마리아나 군도",
  },
  { code: "OM", name: "Oman", korName: "오만" },
  { code: "PW", name: "Palau", korName: "팔라우" },
  { code: "PA", name: "Panama", korName: "파나마" },
  { code: "PY", name: "Paraguay", korName: "파라과이" },
  { code: "PH", name: "Philippines", korName: "필리핀" },
  { code: "PL", name: "Poland", korName: "폴란드" },
  { code: "PR", name: "Puerto Rico", korName: "푸에르토리코" },
  { code: "RE", name: "Réunion", korName: "레위니옹" },
  { code: "RU", name: "Russia", korName: "러시아" },
  { code: "SH", name: "Saint Helena", korName: "세인트 헬레나" },
  { code: "LC", name: "Saint Lucia", korName: "세인트루시아" },
  {
    code: "VC",
    name: "St. Vincent and the Grenadines",
    korName: "세인트빈센트 그레나딘",
  },
  {
    code: "VC",
    name: "St. Vincent Grenadines",
    korName: "세인트빈센트 그레나딘",
  },
  { code: "SM", name: "San Marino", korName: "산마리노" },
  { code: "SA", name: "Saudi Arabia", korName: "사우디아라비아" },
  { code: "SC", name: "Seychelles", korName: "세이셸" },
  { code: "SG", name: "Singapore", korName: "싱가포르" },
  { code: "SI", name: "Slovenia", korName: "슬로베니아" },
  { code: "SO", name: "Somalia", korName: "소말리아" },
  {
    code: "GS",
    name: "South Georgia & the South Sandwich Islands",
    korName: "남조지아 & 남샌드위치 군도",
  },
  { code: "LK", name: "Sri Lanka", korName: "스리랑카" },
  { code: "SR", name: "Suriname", korName: "수리남" },
  { code: "SZ", name: "Eswatini", korName: "에스와티니" },
  { code: "CH", name: "Switzerland", korName: "스위스" },
  { code: "TW", name: "Taiwan", korName: "대만" },
  {
    code: "TZ",
    name: "Tanzania",
    korName: "탄자니아",
  },
  { code: "TG", name: "Togo", korName: "토고" },
  { code: "TO", name: "Tonga", korName: "통가" },
  { code: "TN", name: "Tunisia", korName: "튀니지" },
  { code: "TM", name: "Turkmenistan", korName: "투르크메니스탄" },
  { code: "TV", name: "Tuvalu", korName: "투발루" },
  { code: "UA", name: "Ukraine", korName: "우크라이나" },
  { code: "GB", name: "UK", korName: "영국" },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    korName: "마이너 아우틀링 합중국 군도",
  },
  { code: "UZ", name: "Uzbekistan", korName: "우즈베키스탄" },
  { code: "VA", name: "Vatican City", korName: "바티칸 시국" },
  { code: "VN", name: "Vietnam", korName: "베트남" },
  {
    code: "VG",
    name: "VirginnIslands -British",
    korName: "영령 버진군도",
  },
  { code: "EH", name: "Western Sahara", korName: "서사하라" },
  { code: "YU", name: "Yugoslavia", korName: "유고" },
  { code: "ZM", name: "Zambia", korName: "잠비아" },
  { code: "AL", name: "Albania", korName: "알바니아" },
  { code: "AS", name: "American Samoa", korName: "사모아(미국령)" },
  { code: "AO", name: "Angola", korName: "앙골라" },
  { code: "AQ", name: "Antarctica", korName: "안타티카" },
  { code: "AR", name: "Argentina", korName: "아르헨티나" },
  { code: "AW", name: "Aruba", korName: "아루바" },
  { code: "AT", name: "Austria", korName: "오스트리아" },
  { code: "BS", name: "Bahamas", korName: "바하마" },
  { code: "BD", name: "Bangladesh", korName: "방글라데시" },
  { code: "BY", name: "Belarus", korName: "벨라루스" },
  { code: "BZ", name: "Belize", korName: "벨리즈" },
  { code: "BM", name: "Bermuda", korName: "버뮤다" },
  { code: "BO", name: "Bolivia", korName: "볼리비아" },
  { code: "BW", name: "Botswana", korName: "보츠와나" },
  { code: "BR", name: "Brazil", korName: "브라질" },
  { code: "BN", name: "Brunei", korName: "브루나이" },
  { code: "BF", name: "Burkina Faso", korName: "부르키나파소" },
  { code: "KH", name: "Cambodia", korName: "캄보디아" },
  { code: "CA", name: "Canada", korName: "캐나다" },
  { code: "KY", name: "Cayman Islands", korName: "영령 캐이맨 군도" },
  { code: "TD", name: "Chad", korName: "차드" },
  { code: "CN", name: "China", korName: "중국" },
  { code: "CC", name: "CocosKeeling Islands", korName: "코스 군도" },
  { code: "KM", name: "Comoros", korName: "코모로스" },
  { code: "KM", name: "Comoros", korName: "코모로" },
  { code: "CK", name: "Cook Islands", korName: "쿡제도" },
  { code: "CI", name: "Ivory Coast", korName: "코트디부아르" },
  { code: "CU", name: "Cuba", korName: "쿠바" },
  { code: "CZ", name: "Czechia", korName: "체코" },
  { code: "DJ", name: "Djibouti", korName: "지부티" },
  { code: "DO", name: "Dominican Republic", korName: "도미니카 공화국" },
  { code: "EC", name: "Ecuador", korName: "에콰도르" },
  { code: "SV", name: "El Salvador", korName: "엘살바도르" },
  { code: "ER", name: "Eritrea", korName: "에리트리아" },
  { code: "ET", name: "Ethiopia", korName: "에티오피아" },
  { code: "FO", name: "Faeroe Islands", korName: "페로 제도" },
  { code: "FI", name: "Finland", korName: "핀란드" },
  { code: "GF", name: "French Guiana", korName: "불령 가이아나" },
  {
    code: "TF",
    name: "French Southern Territories",
    korName: "불령 남부지역",
  },
  { code: "GM", name: "Gambia", korName: "감비아" },
  { code: "DE", name: "Germany", korName: "독일" },
  { code: "GI", name: "Gibraltar", korName: "지브랄타" },
  { code: "GL", name: "Greenland", korName: "그린랜드" },
  { code: "GP", name: "Guadeloupe", korName: "과델로프" },
  { code: "GT", name: "Guatemala", korName: "과테말라" },
  { code: "GW", name: "Guinea-Bissau", korName: "기네비소" },
  { code: "HT", name: "Haiti", korName: "아이티" },
  { code: "HK", name: "Hong Kong", korName: "홍콩" },
  { code: "IS", name: "Iceland", korName: "아이슬란드" },
  { code: "ID", name: "Indonesia", korName: "인도네시아" },
  { code: "IQ", name: "Iraq", korName: "이라크" },
  { code: "IL", name: "Israel", korName: "이스라엘" },
  { code: "JM", name: "Jamaica", korName: "자메이카" },
  { code: "JO", name: "Jordan", korName: "요르단" },
  { code: "JO", name: "Jordan", korName: "조르단" },
  { code: "KE", name: "Kenya", korName: "케냐" },
  {
    code: "KP",
    name: "Korea, Democratic People's Republic of",
    korName: "북한",
  },
  { code: "KW", name: "Kuwait", korName: "쿠웨이트" },
  {
    code: "LA",
    name: "Laos",
    korName: "라오스",
  },
  { code: "LB", name: "Lebanon", korName: "레바논" },
  { code: "LR", name: "Liberia", korName: "라이베리아" },
  { code: "LI", name: "Liechtenstein", korName: "리히텐슈타인" },
  { code: "LU", name: "Luxembourg", korName: "룩셈부르그" },
  {
    code: "MK",
    name: "North Macedonia",
    korName: "북 마케도니아",
  },
  { code: "MW", name: "Malawi", korName: "말라위" },
  { code: "MV", name: "Maldives", korName: "몰디브" },
  { code: "MT", name: "Malta", korName: "몰타" },
  { code: "MQ", name: "Martinique", korName: "마티니크" },
  { code: "MU", name: "Mauritius", korName: "모리셔스" },
  { code: "MU", name: "Mauritius", korName: "모리티우스" },
  { code: "MX", name: "Mexico", korName: "멕시코" },
  { code: "MD", name: "Moldova", korName: "몰도바" },
  { code: "MN", name: "Mongolia", korName: "몽골" },
  { code: "MA", name: "Morocco", korName: "모로코" },
  { code: "MM", name: "Myanmar", korName: "미얀마" },
  { code: "NR", name: "Nauru", korName: "나우루" },
  { code: "NL", name: "Netherlands", korName: "네덜란드" },
  { code: "NC", name: "New Caledonia", korName: "뉴 칼레도니아" },
  { code: "NI", name: "Nicaragua", korName: "니카라과" },
  { code: "NG", name: "Nigeria", korName: "나이지리아" },
  { code: "NF", name: "Norfolk Island", korName: "노폴크 아일랜드" },
  { code: "NO", name: "Norway", korName: "노르웨이" },
  { code: "PK", name: "Pakistan", korName: "파키스탄" },
  {
    code: "PS",
    name: "Palestine",
    korName: "팔레스타인",
  },
  { code: "PG", name: "Papua New Guinea", korName: "파푸아뉴기니" },
  { code: "PE", name: "Peru", korName: "페루" },
  { code: "PN", name: "Pitcairn", korName: "피트카이른" },
  { code: "PT", name: "Portugal", korName: "포루투갈" },
  { code: "QA", name: "Qatar", korName: "카타르" },
  { code: "RO", name: "Romania", korName: "루마니아" },
  { code: "RW", name: "Rwanda", korName: "르완다" },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    korName: "세인트키츠 네비스",
  },
  {
    code: "PM",
    name: "Saint Pierre Miquelon",
    korName: "생피에르 미클롱",
  },
  { code: "WS", name: "Samoa", korName: "사모아" },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    korName: "상토메 프린스페",
  },
  { code: "SN", name: "Senegal", korName: "세네갈" },
  { code: "SL", name: "Sierra Leone", korName: "시에라 리온" },
  { code: "SK", name: "Slovakia", korName: "슬로바키아" },
  { code: "SB", name: "Solomon Islands", korName: "솔로몬제도" },
  { code: "ZA", name: "South Africa", korName: "남아프리카공화국" },
  { code: "ES", name: "Spain", korName: "스페인" },
  { code: "SD", name: "Sudan", korName: "수단" },
  { code: "SS", name: "South Sudan", korName: "수단" },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    korName: "스발비드 군도",
  },
  { code: "SE", name: "Sweden", korName: "스웨덴" },
  { code: "SY", name: "Syria", korName: "시리아" },
  { code: "TJ", name: "Tajikistan", korName: "타지키스탄" },
  { code: "TH", name: "Thailand", korName: "태국" },
  { code: "TK", name: "Tokelau", korName: "토켈라우" },
  {
    code: "TT",
    name: "Trinidad And Tobago",
    korName: "트리니다드 토바고",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    korName: "트리니다드 토바고",
  },
  { code: "TR", name: "Turkey", korName: "터키" },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    korName: "투르크 & 카이코스 군도",
  },
  {
    code: "TC",
    name: "Turks and Caicos",
    korName: "터크스 케이커스 제도",
  },
  { code: "UG", name: "Uganda", korName: "우간다" },
  {
    code: "AE",
    name: "UAE",
    korName: "아랍에미리트",
  },
  {
    code: "AE",
    name: "UAE",
    korName: "UAE",
  },
  { code: "US", name: "USA", korName: "미국" },
  { code: "UY", name: "Uruguay", korName: "우루과이" },
  { code: "VU", name: "Vanuatu", korName: "바누아투" },
  { code: "VE", name: "Venezuela", korName: "베네수엘라" },
  { code: "VI", name: "Virgin Islands-U.S.", korName: "미령 버진군도" },
  { code: "VI", name: "U.S. Virgin Islands", korName: "미국령 버진아일랜드" },
  {
    code: "VG",
    name: "British Virgin Islands",
    korName: "영국령 버진아일랜드",
  },
  {
    code: "WF",
    name: "Wallis and futuna Islands",
    korName: "왈라스 & 퓨투나 군도",
  },
  { code: "YE", name: "Yemen", korName: "예멘" },
  { code: "ZR", name: "Zaire", korName: "자이레" },
  { code: "ZW", name: "Zimbabwe", korName: "짐바브웨" },
  { code: "JP", name: "Diamond Princess", korName: "일본 크루즈" },
  { code: "MF", name: "Saint Martin", korName: "세인트마틴 섬" },
  { code: "GB", name: "Channel Islands", korName: "채널 제도" },
  { code: "BL", name: "St. Barth", korName: "생바르텔레미" },
  { code: "RS", name: "Serbia", korName: "세르비아" },
  { code: "CD", name: "DRC", korName: "민주콩고" },
  { code: "ME", name: "Montenegro", korName: "몬테네그로" },
  { code: "CW", name: "Curaçao", korName: "퀴라소" },
  { code: "SX", name: "Sint Maarten", korName: "신트마르턴" },
  { code: "IM", name: "Isle of Man", korName: "맨섬" },
  { code: "", name: "MS Zaandam", korName: "잔담호" },
  { code: "NL", name: "Caribbean Netherlands", korName: "카리브 네덜란드" },
  { code: "WORLD", name: "World", korName: "전세계" },
  {
    code: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    korName: "카리브 네덜란드",
  },
  {
    code: "JE",
    name: "Jersey",
    korName: "저지섬",
  },
];
